---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ensc7151/public_html/sisikat
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp laporan.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH

